### ISSUE TITLE
Todo App 요구사항 명세서 작성. 

### ISSUE THREAD

**Issue by dormirMais** [dormirMais/pre-project-example#1]
### 만들고자 하는 기능이 무엇인가요?
ex) Todo 생성기능

### 해당 기능을 구현하기 위해 할 일이 무엇인가요?
1. [x] 추가를 누를시에 todo list가 추가된다.
2. [x] todo list를 누르면 done/undone 여부가 초록색/빨간색으로 표시된다.
3. [x] 삭제버튼을 누르면 todo list가 삭제된다.

### 예상 작업시간.
ex) 3H
